---
- hosts: all
  remote_user: pod

  vars:
    # Username
    user: pod
    # Timezone
    timezone: 'Europe/Paris'

  tasks:

    ###################
    # User Management 
    ###################
    #- name: Create user pod
    #  sudo: yes
    #  user: name={{ user }} group="pod"
    #        comment="{{ user }} user"
    #        shell=/bin/bash

    - name: configure sudoers
      sudo: yes
      lineinfile: dest=/etc/sudoers backup=yes state=present regexp=^%{{ user }} insertafter="^# %wheel" line='%{{ user }} ALL=(ALL) ALL'
      tags: config-sudoers



    ###################
    # Time management 
    ###################
    - name: Set local timezone
      copy: content={{ timezone }}
            dest=/etc/timezone
      notify: update tzdata

    - name: Install NTP (and update apt cache for the first install)
      sudo: yes
      remote_user: root
      apt: name=ntp state=present
           update_cache=yes

    - name: Start the ntp service
      service: name=ntp state=started enabled=true

    ############
    # Security 
    ############
    - name: Install fail2ban
      apt: name=fail2ban state=present

    - name: Start fail2ban service
      service: name=fail2ban state=started enabled=true


    ###################
    # Python / Virtualenv
    ###################

    - name: Install environnement systeme
      apt: name={{ item }} state=latest
      sudo: yes
      remote_user: root
      with_items:
        - python-pip
        - python-dev
        - build-essential
        - libmysqlclient-dev
        - graphviz
        - libgraphviz-dev
        - pkg-config
        - libldap2-dev
        - libsasl2-dev
        - libssl-dev
        - libjpeg-dev

    - name: Install usefull system tools
      sudo: yes
      apt: name={{ item }} state=present
      with_items:
        - vim
        - git

    - name: Install virtualenvwrapper
      sudo: yes
      pip: name=virtualenvwrapper

     ##########################################
     # Insert 2 lines at the end of bashrc file
     ##########################################

    #- name: add export WORKON_HOME=$HOME/.virtualenvs at the end of the file
     # lineinfile: dest=/home/pod/.bashrc
      #            insertafter=EOF
       #           line='export WORKON_HOME=$HOME/.virtualenvs\nsource '"/usr/local/bin/virtualenvwrapper.sh"''

    - name: add export WORKON_HOME=$HOME/.virtualenvs at the end of the file
      lineinfile:
        dest: /home/pod/.bashrc
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'export WORKON_HOME', line: 'export WORKON_HOME=$HOME/.virtualenvs' }
        - { regexp: 'source /usr/local', line: 'source /usr/local/bin/virtualenvwrapper.sh' }

    - name: source bashrc
      sudo: no   
      shell: source $HOME/.bashrc 
      args:
         executable: /bin/bash

    - name: Run 'which django_pod'
      shell: >
        executable=/bin/bash
        source `which virtualenvwrapper.sh` && mkvirtualenv django_pod
      register: run_cmd

    - name: emplacement project
      sudo: yes
      file: path=/usr/local/django_projects state=directory

    - name: lien symbolique de l'emplacement
      file: src=/usr/local/django_projects dest=/../home/pod/django_projects state=link

    - name: droit du répertoire django_projects
      sudo: yes
      remote_user: root
      shell: chown -R pod:pod /usr/local/django_projects 

     #########################
     # Deploying Pod_project 
     #########################
    - name: ajout couleur prompt 
      shell: "sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' /home/{{user}}/.bashrc"

    - name: ajout option "ls -l" -> "ll"
      #shell: "sed -i 's/#alias ll=\'ls -l\'/alias ll=\'ls -l\'/' /home/{{user}}/.bashrc"
      replace:
        dest=/home/{{user}}/.bashrc
        regexp="#alias ll=\'ls -l\'"
        replace="alias ll=\'ls -l\'"
        backup=yes


    - name: Git clone/pull pod 
      git: repo="https://github.com/SemmLille/pod.git"  
           dest=/usr/local/django_projects/pod

    - name: git pull dev
      shell: git pull origin dev
      args:
         chdir: /home/pod/django_projects/pod
         executable: /bin/bash

    - name: Install librairies python
      sudo: yes
      shell: pip install -r /home/pod/django_projects/pod/requirements.txt

    - name: Copy fichier configuration wsgi-sample
      copy: src=/home/pod/django_projects/pod/pod_project/pod_project/wsgi-sample.py
            dest=/home/pod/django_projects/pod/pod_project/pod_project/wsgi.py

    - name: Copy fichier configuration settings-sample.py
      copy: src=/home/pod/django_projects/pod/pod_project/pod_project/settings-sample.py
            dest=/home/pod/django_projects/pod/pod_project/pod_project/settings.py

    - name : creation bdd
      shell: python manage.py syncdb --noinput
      args:
         chdir: /home/pod/django_projects/pod/pod_project/
         executable: /bin/bash

    - name : migration des tables
      shell: python ./manage.py migrate
      args:
         chdir: /home/pod/django_projects/pod/pod_project/
         executable: /bin/bash

    #installation FFMPEG
    - name: creation dossier FFMPEG
      shell: mkdir ffmpeg
      sudo: yes
      ignore_errors: yes
      args:
         chdir: /usr/local/
         executable: /bin/bash


    - name: download ffmeg static file
      sudo: yes
      get_url: url=http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz dest=/usr/local/ffmeg 

    #- unarchive: src=/usr/local/ffmeg/ffmpeg.static.64bit.latest.tar.gz dest=/usr/local/ffmeg/
    #  sudo: yes

    - name: droit en lecture et en ecriture ffmpeg” et “ffprobe”
      sudo: yes
      remote_user: root
      shell: chmod 755 ff*
      args:
         chdir: /usr/local/ffmpeg
         executable: /bin/bash

    #installation elasticsearch

    - name :  Install openjdk 7
      sudo: yes
      remote_user: root
      shell: aptitude -y install openjdk-7-jre-headless 
      args:
         executable: /bin/bash

    - name :  Download and install the Public Signing Key
      shell: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
      args:
         executable: /bin/bash

    - name :  Add the repository definition to your /etc/apt/sources.list file
      shell: echo "deb http://packages.elastic.co/elasticsearch/1.5/debian stable main" | sudo tee -a /etc/apt/sources.list
      args:
         executable: /bin/bash

    - name :  install elasticsearch
      shell: "sudo apt-get update && sudo apt-get install elasticsearch"
      args:
         executable: /bin/bash

    - name :   automatically start during bootup
      shell: "sudo update-rc.d elasticsearch defaults 95 10"
      args:
         executable: /bin/bash

    - name: change configuration
      sudo: yes
      remote_user: root
      lineinfile:
        dest: "/etc/elasticsearch/elasticsearch-test.yml"
        regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
        backup: yes
        state: present
      with_items:
        - { regexp: '#cluster.name: elasticsearch', line: 'cluster.name: pod' }
        - { regexp: '#node.name: "Franz Kafka"', line: 'node.name: "Pod1"' }
        - { regexp: '#network.host: 192.168.0.1', line: 'network.host: 127.0.0.1' }
        - { regexp: '#path.logs: /path/to/logs', line: 'path.logs: /usr/local/var/log' }
        - { regexp: '#path.data: /path/to/data1,/path/to/data2', line: 'path.data: /usr/local/var/log' }
        - { regexp: '#discovery.zen.ping.multicast.enabled: false', line: 'discovery.zen.ping.multicast.enabled: false' }
        - { regexp: '#discovery.zen.ping.unicast.hosts:["host1", "host2:port"]', line: 'discovery.zen.ping.unicast.hosts: ["127.0.0.1"]' }

    - name : lancement des tests unitaires
      shell: python manage.py test core pods.tests.tests_models pods.tests.tests_views pods.tests.tests_delete_video
      args:
         chdir: /home/pod/django_projects/pod/pod_project/
         executable: /bin/bash


    #- name : Validation et lancement du serveur .. si il n'y a pas d'erreur vous pouvez le quitter "Control-c"
    #  shell: python django_projects/pod/pod_project/manage.py runserver
    #  args:
    #     executable: /bin/bash

    #Django admin.py create-user
  ###################
  # Handlers
  ###################
  handlers:
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

