---
- hosts: all
  remote_user: pod

  vars:
    # Username
    user: pod
    save_modif: false

  tasks:
    #creation base de données + tables à la main  
    - name: remplace la database sqlite par Mysql
      replace:
        dest="/home/pod/django_projects/pod/pod_project/pod_project/settings_test.py"
        regexp="\'default\'"\:" { {{'\n'}}
              \'ENGINE\'"\:" \'django.db.backends.sqlite3\', {{'\n'}}
              \'NAME\' "\:" \'db.sqlite\',{{'\n'}}
              }{{'\n'}}
              }{{'\n'}}"
        replace=''
        backup=yes



    #- name: remplace la database sqlite par Mysql 1
    #  lineinfile:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings.py"
    #    insertbefore='^#Configuration MySql'
    #    backup=yes
    #    line="\"\"\" "

    #- name: remplace la database sqlite par Mysql 2
    #  lineinfile:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings.py"
    #    insertafter="^DATABASES"
    #    backup=yes
    #    line=" \"\"\" "

    #- name: remplace la database sqlite par Mysql 3
    #  lineinfile:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings.py"
    #    insertbefore='^# Internationalisation'
    #    backup=yes
    #    line=" } "

    #- name: remplace la database sqlite par Mysql 1
    #  replace:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings_test.py"
    #    regexp="\'default\'"\:" { {{'\n'}}"
    #    replace=' '
    #    backup="yes"

    #- name: remplace la database sqlite par Mysql 2
    #  replace:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings_test.py"
    #    regexp="\'ENGINE\'"\:" \'django.db.backends.sqlite3\', {{'\n'}}"
    #    replace=' '
    #    backup="yes"

    #- name: remplace la database sqlite par Mysql 3
    #  replace:
    #    dest="/home/pod/django_projects/pod/pod_project/pod_project/settings_test.py"
    #    regexp="\'NAME\'"\:" \'db.sqlite\', {{'\n'}}
    #           }{{'\n'}} }{{'\n'}}"
    #    replace=' '
    #    backup="yes"
        #"\:"\'django.db.backends.sqlite3\', {{'\n'}}"
        #\'ENGINE\'"\:"\'django.db.backends.sqlite3\', {{'\n'}}
              # \'NAME\'"\:"\'db.sqlite\',{{'\n'}}
              # 