---
- hosts: all
  remote_user: pod

  vars:
    # Username
    user: pod
    save_modif: false
  roles:
    - yaegashi.blockinfile
  tasks:
    - name: python collectstatic
      shell: python manage.py collectstatic --noinput
      args:
         chdir: /home/pod/django_projects/pod/pod_project
         executable: /bin/bash